# This workflow applies formatted syntax of the code using spotless.
name: Syntax Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Set permissions for the workflow
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "spotless"
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # If the action is triggered by Dependabot, do not run these checks
    if: ${{ github.actor != 'dependabot[bot]' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      # Setup Java 17
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Runs our formatter for easier code review
      - name: Run spotlessApply
        run: ./gradlew spotlessApply

      # Check if there are any changes, if so, create a commit and push it
      - name: Create commit of formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Spotless] Apply formatting"
